[package]
name = "nsq"
version = "0.0.1"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
repository = "https://github.com/gsquire/nsq-rs"
description = "An unofficial NSQ client"
documentation = "https://docs.rs/nsq"
license = "MIT"

[dependencies]
